### ISSUE TITLE
Question about the stucture picture

### ISSUE THREAD

**Issue by ccxi1008** [huanngzh/Parts2Whole#10]
Hi, I want to generate the whole body. How can I get some whole body stucture picture in densepose like those in tsetset? Are they generated by Densepose code?

**Comment by huanngzh** [comment]
We provide a large set of densepose images [here](https://huggingface.co/datasets/huanngzh/DeepFashion-MultiModal-Parts2Whole/tree/main) (refer to densepose.zip). You can also generate densepose maps using [Densepose](https://github.com/facebookresearch/DensePose).
