### ISSUE TITLE
question about enhanced mask-guided subject selection

### ISSUE THREAD

**Issue by 1851759** [huanngzh/Parts2Whole#14]
I see you used "ref_unet(latents_ref_img, ref_timesteps, text_encoder_hidden_states, cross_attention_kwargs={"hidden_states_mask": vmask}, )" to realize the enhanced mask-guided subject selection.But I do not know how it works.Could you explain it or share some docs with me ? Thans a lot.

**Comment by huanngzh** [comment]
You can check `ReferenceAttentionControl` in `parts2whole/models/mutual_self_attention.py`. This class is the core code for the feature interaction between denoising unet and reference unet, implemented by a `bank`.

For the enhanced mask-guided subject selection, we pass `hidden_states_mask` in the `cross_attention_kwargs`, and implement the mask process in the `write` mode (i.e. for reference unet).

https://github.com/huanngzh/Parts2Whole/blob/e21765559185eb58b57ce2aeb28d774604ebf3ec/parts2whole/models/mutual_self_attention.py#L123C13-L170C22

You can see, in the `write` mode, `hidden_states_mask` will be augmented with a kernel and used to select the features from the image features in the self-attention layers.

Hope this helps clear up your confusion.

**Comment by 1851759** [comment]
Thanks for your reply! It helps me a lot!
