### ISSUE TITLE
Will it work with DW Pose as well?

### ISSUE THREAD

**Issue by adityapandey9** [huanngzh/Parts2Whole#3]
Hi, Thanks for the awesome project. I am using it, but just have a question. Will it work with DW Pose as well? I have tried it but it did not work. Can you please let me know if I am doing anything wrong? Thank you in advance :)

**Comment by huanngzh** [comment]
Hi, we currently only release the model that supports control of densepose. We will soon release the model that work with DWPose.

**Comment by adityapandey9** [comment]
Hi, @huanngzh any timeline for the dw-pose or open-pose support? Thank you in advance :)
