### ISSUE TITLE
Humans do not look real when changing poses.

### ISSUE THREAD

**Issue by adityapandey9** [huanngzh/Parts2Whole#9]
Hi, Sorry for disturbing you again. When I tried to use your model to create a different pose on same image, I was getting a non-realistic human. Could you have a look? Do you know how to fix this or improve this? 

Upper body image:
![2](https://github.com/user-attachments/assets/ce4162c5-38b7-444f-babf-70e473a5127e)

The whole body image generated via the model 
![2_1](https://github.com/user-attachments/assets/f43fd3d5-4fa7-42e1-aea9-0bbb1aa06f4b)

**Comment by huanngzh** [comment]
Hi, the current model is controlled by densepose maps. If the input densepose is too different from the expected human body shape, strange results may be generated. Our model is not designed for pose adaptation. Currently, some pose estimation methods or pose editing tools can be used to solve this problem.
